### ISSUE TITLE
Correction Semaine 1

### ISSUE THREAD

**Issue by CodeboxxCoaches** [plemire/Rocket_Elevators_Controllers#1]
Le projet est une bonne base pour la semaine qui commence, par contre quelques problèmes majeurs:

- Dans moveElevator, tu vérifies elevatorDirection... mais je n'ai vu nul part dans le commercial à quel moment on modifie elevatorDirection à up ou down en dehors des IF. Ce qui fait que malheureusement les ascenseurs ne bougent jamais.
- Dans 
```
SEQUENCE floorNumberButton USING chosenElevator AND requestedFloor
    SET floorButtonState TO TRUE
    SET elevatorDirection TO direction
    IF requestedFloor IS NOT IN floorsArray
        CALL insertToFloorArray WITH chosenElevator AND requestedFloor AND direction
    END IF
    CALL MoveElevator WITH currentElevator AND requestedFloor AND direction
END SEQUENCE
```
`SET elevatorDirection TO direction`... d'où vient la variable direction? Même chose pour `CALL MoveElevator WITH currentElevator AND requestedFloor AND direction`

Un peu moins majeur:
- Dans selectColumn, on recréé à chaque fois les nouvelles colonnes... On devrait faire cela juste une fois au début.

Ce sont des détails qui font que malheurement les scénarios ne fonctionnent pas. Il faudra revoir ça cette semaine, ce sera bien sûr plus facile à faire avec le code, mais il faut faire encore plus attention à tous les petits détails.
Ceci étant dit, le pseudocode est bien écrit et très clair. Gardes le même genre de structure dans ton code.

**Comment by plemire** [comment]
Merci pour les commentaires, je m'assure d'en tenir compte dans mon code.
