### ISSUE TITLE
Correction semaine 2

### ISSUE THREAD

**Issue by CodeboxxCoaches** [plemire/Rocket_Elevators_Controllers#2]
- Bon travail. C'est clean, tout fonctionne et ton programme de test est excellent. Pour que ce soit encore plus clean on aurait pu mettre les fonctions scenarios dans un fichier différent, juste pour alléger le code. Les commentaires un peu partout dans le code sont super.
- La structure et les liens entre tes classes auraient pu êtres mieux structurés, le cas idéal étant de ne créer manuellement que le contrôlleur en spécifiant le nombre de colonnes et d'ascenseurs pour qu'ils soient créés automatiquement. Je vois pour le python qu'il y a une classe Column, mais qui ne semble pas être utilisée?
- Bon travail pour le bonus avec ruby!
- Il faudra voir cette semaine pour rendre ton programme adaptif à tout contexte ou scénarios.

Très bon projet somme toutes, continues comme ça!

**Comment by plemire** [comment]
Merci pour les commentaires, je vais assurément en tenir compte dans ce que je vais livrer cette semaine.
